# Makefile for Dining Philosopher problem

all: compile run clean

compile: Dining_Philosophers.c
	gcc -o Dining_Philosophers Dining_Philosophers.c 

run: compile
	./Dining_Philosophers

clean:
	rm -rf Dining_Philosophers